## 1st assignment
We want the hours of service for each unique (stop_id, route_id) pair.  Please submit the Python code and your output in the following format:
 
Stop_id, route_id, earliest arrival time, latest  departure time, hours of service, Monday.
Please also provide the grand total of the hours of service (for all stops and routes) at the top of the sheet.
 
## 2nd assignment
Please submit your Python code and output in the following format:
Zone_id label (not coordinates), 1st nearest neighbor zone label (not coordinates) : distance (in miles), â€¦ , 6th nearest neighbor zone label (not coordinates) : distance (in miles).

In [1]:
import pandas as pd

In [2]:
cal_df = pd.read_table('./calendar.txt', sep=",", header=0, names=['service_id', 'monday', 'tuesday','wednesday','thursday','friday'\
                         ,'saturday','sunday','start_date','end_date'])
#df.columns =

In [3]:
cal_df

,service_id,monday,tuesday,wednesday,thursday,friday,saturday,sunday,start_date,end_date
0,1,0,0,0,0,0,1,0,20111113,20120114
1,2,0,0,0,0,0,0,1,20111113,20120114
2,3,1,1,1,1,1,0,0,20111113,20120114
3,4,0,0,0,0,0,1,0,20111113,20120114
4,5,0,0,0,0,0,0,1,20111113,20120114
5,6,1,1,1,1,1,0,0,20111113,20120114
6,7,0,0,0,0,0,1,0,20111113,20120114
7,8,0,0,0,0,0,0,1,20111113,20120114
8,9,1,1,0,1,0,0,0,20111113,20120114
9,10,1,1,1,1,1,0,0,20111113,20120114
10,11,1,1,1,1,1,0,0,20111113,20120114
11,12,0,0,1,0,1,0,0,20111113,20120114
12,13,0,0,0,0,0,1,0,20111113,20120114
13,14,1,0,0,0,0,0,0,20111113,20120114
14,15,1,1,1,1,1,0,0,20111113,20120114
15,16,1,1,1,1,1,0,0,20111113,20120114
16,17,0,0,0,0,0,0,1,20111113,20120114
17,18,0,1,1,1,1,0,0,20111113,20120114
18,19,1,1,1,1,1,0,0,20111113,20120114
19,20,0,0,0,0,1,0,0,20111113,20120114
20,21,1,0,0,0,0,0,0,20111113,20120114
21,22,1,1,1,1,0,0,0,20111113,20120114
22,23,0,1,1,1,1,0,0,20111113,20120114
23,24,0,0,0,0,1,0,0,20111113,20120114
24,25,1,1,0,1,0,0,0,20111113,20120114
25,26,1,1,1,1,0,0,0,20111113,20120114
26,27,1,0,0,0,0,0,0,20111113,20120114
27,28,0,0,0,0,0,1,0,20111113,20120114
28,29,0,0,0,0,0,0,1,20111113,20120114
29,30,0,1,1,1,1,0,0,20111113,20120114
30,31,1,1,1,1,1,0,0,20111113,20120114
31,32,1,1,1,1,1,0,0,20111113,20120114
32,33,1,1,1,1,1,0,0,20111113,20120114
33,34,0,0,1,0,1,0,0,20111113,20120114
34,39,1,1,1,1,1,0,0,20111113,20120114
35,40,0,0,0,0,1,0,0,20111113,20120114
36,41,1,1,1,1,0,0,0,20111113,20120114
37,42,1,1,1,1,1,0,0,20111113,20120114
38,43,1,1,1,1,1,0,0,20111113,20120114
39,44,0,0,1,0,0,0,0,20111113,20120114
40,45,0,0,0,0,0,1,0,20111113,20120114
41,46,1,1,1,1,1,0,0,20111113,20120114
42,47,0,0,1,0,0,0,0,20111113,20120114
43,48,0,0,0,0,1,0,0,20111113,20120114

In [4]:
route_df = pd.read_table('./routes.txt', sep=",", header=0, names=['route_id','route_short_name',\
                                                                   'route_long_name','route_type','route_url'])

In [5]:
route_df

,route_id,route_short_name,route_long_name,route_type,route_url
0,37692,665,Darien-Westmont,3,http://www.pacebus.com/sub/schedules/route_det...
1,37571,821,IL 53/83rd St.-Belmont Feeder,3,http://www.pacebus.com/sub/schedules/route_det...
2,37536,663,Darien-Clarendon Hills,3,http://www.pacebus.com/sub/schedules/route_det...
3,37523,664,Willowbrook-Clarendon Hills,3,http://www.pacebus.com/sub/schedules/route_det...
4,37563,662,South Central Westmont Feeder,3,http://www.pacebus.com/sub/schedules/route_det...
5,37544,661,Southwest Westmont Feeder,3,http://www.pacebus.com/sub/schedules/route_det...
6,37694,826,South Lisle,3,http://www.pacebus.com/sub/schedules/route_det...
7,37686,828,North Lisle,3,http://www.pacebus.com/sub/schedules/route_det...
8,37590,824,East Bolingbrook Lisle Feeder,3,http://www.pacebus.com/sub/schedules/route_det...
9,37521,827,Green Trails-Steeple Run,3,http://www.pacebus.com/sub/schedules/route_det...
10,37538,820,University Heights-Hobson Creek Lis,3,http://www.pacebus.com/sub/schedules/route_det...
11,37517,829,Lisle-Naperville Office Corridor,3,http://www.pacebus.com/sub/schedules/route_det...
12,37668,825,Central Bolingbrook-Lisle Feeder,3,http://www.pacebus.com/sub/schedules/route_det...
13,37632,318,West North Avenue,3,http://www.pacebus.com/sub/schedules/route_det...
14,37531,308,Medical Center,3,http://www.pacebus.com/sub/schedules/route_det...
15,37603,332,River - York Roads,3,http://www.pacebus.com/sub/schedules/route_det...
16,37493,317,Westchester,3,http://www.pacebus.com/sub/schedules/route_det...
17,37605,307,Harlem,3,http://www.pacebus.com/sub/schedules/route_det...
18,37547,303,Madison Street - 19th Avenue,3,http://www.pacebus.com/sub/schedules/route_det...
19,37649,311,Oak Park Avenue,3,http://www.pacebus.com/sub/schedules/route_det...
20,37495,305,Cicero - River Forest,3,http://www.pacebus.com/sub/schedules/route_det...
21,37562,392,Little Village - United Parcel Service,3,http://www.pacebus.com/sub/schedules/route_det...
22,37522,390,Midway CTA - UPS Hodgkins,3,http://www.pacebus.com/sub/schedules/route_det...
23,37498,330,Mannheim - LaGrange Roads,3,http://www.pacebus.com/sub/schedules/route_det...
24,37542,301,Roosevelt Road,3,http://www.pacebus.com/sub/schedules/route_det...
25,37555,319,Grand Avenue,3,http://www.pacebus.com/sub/schedules/route_det...
26,37576,757,Northwest Connection,3,http://www.pacebus.com/sub/schedules/route_det...
27,37591,315,Austin - Ridgeland,3,http://www.pacebus.com/sub/schedules/route_det...
28,37561,320,Madison Street,3,http://www.pacebus.com/sub/schedules/route_det...
29,37698,313,St. Charles Road,3,http://www.pacebus.com/sub/schedules/route_det...
...,...,...,...,...,...
169,37614,629,Braeside Shuttle Bug 9,3,http://www.pacebus.com/sub/schedules/route_det...
170,37607,668,Burr Ridge-Hinsdale Feeder,3,http://www.pacebus.com/sub/schedules/route_det...
171,37539,669,Western Springs-Indian Head Park,3,http://www.pacebus.com/sub/schedules/route_det...
172,37510,834,Joliet-Downers Grove,3,http://www.pacebus.com/sub/schedules/route_det...
173,37589,511,Joliet-Elwood-Deer Run,3,http://www.pacebus.com/sub/schedules/route_det...
174,37572,855,Plainfield-East Loop Express,3,http://www.pacebus.com/sub/schedules/route_det...
175,37512,507,Plainfield,3,http://www.pacebus.com/sub/schedules/route_det...
176,37637,755,Plainfield - IMD Express,3,http://www.pacebus.com/sub/schedules/route_det...
177,37600,505,West Joliet Loop,3,http://www.pacebus.com/sub/schedules/route_det...
178,37641,504,South Joliet,3,http://www.pacebus.com/sub/schedules/route_det...
179,37516,832,Joliet - Orland Square,3,http://www.pacebus.com/sub/schedules/route_det...
180,37663,501,West Jefferson,3,http://www.pacebus.com/sub/schedules/route_det...
181,37634,508,East Joliet,3,http://www.pacebus.com/sub/schedules/route_det...
182,37608,509,Forest Park,3,http://www.pacebus.com/sub/schedules/route_det...
183,37657,602,Higgins - Salem - Cedarcrest,3,http://www.pacebus.com/sub/schedules/route_det...
184,37650,802,Aurora-St. Charles,3,http://www.pacebus.com/sub/schedules/route_det...
185,37687,530,West Galena-Westfield Shoppingtown Fox Valley Ctr,3,http://www.pacebus.com/sub/schedules/route_det...
186,37630,529,Randall Road - 5th Street,3,http://www.pacebus.com/sub/schedules/route_det...
187,37669,533,Molitor,3,http://www.pacebus.com/sub/schedules/route_det...
188,37494,521,East Circulator,3,http://www.pacebus.com/sub/schedules/route_det...
189,37564,524,West Aurora Circulator,3,http://www.pacebus.com/sub/schedules/route_det...
190,37532,532,Illinois Avenue,3,http://www.pacebus.com/sub/schedules/route_det...
191,37585,534,Fox Valley Villages / Rt 59 Metra Station,3,http://www.pacebus.com/sub/schedules/route_det...
192,37675,907,Oswego- Aurora Metra Shuttle,3,http://www.pacebus.com/sub/schedules/route_det...
193,37552,528,Aurora Tran. Ctr. - Rush-Copley Med,3,http://www.pacebus.com/sub/schedules/route_det...
194,37595,714,College of DuPage-Naperville-Wheaton Connector,3,http://www.pacebus.com/sub/schedules/route_det...
195,37500,462,Southwest Downers Grove,3,http://www.pacebus.com/sub/schedules/route_det...
196,37639,463,Southeast Downers Grove,3,http://www.pacebus.com/sub/schedules/route_det...
197,37581,461,North Downers Grove,3,http://www.pacebus.com/sub/schedules/route_det...
198,37501,464,West Downers Grove,3,http://www.pacebus.com/sub/schedules/route_det...

In [6]:
stoptime_df = pd.read_table('./stop_times.txt', sep=",", header=0, names=['trip_id','arrival_time','departure_time'\
                                                                          ,'stop_id','stop_sequence'])

In [7]:
stoptime_df

        trip_id arrival_time departure_time  stop_id  stop_sequence
0       1897634     05:30:00       05:30:00    34922              2
1       1897634     05:30:00       05:30:00    34923              3
2       1897634     05:30:00       05:30:00    34924              4
3       1897634     05:30:00       05:30:00    34925              5
4       1897634     05:32:00       05:32:00    34926              6
5       1897634     05:32:00       05:32:00    34927              7
6       1897634     05:32:00       05:32:00    34928              8
7       1897634     05:32:00       05:32:00    34929              9
8       1897634     05:32:00       05:32:00    34930             10
9       1897634     05:32:00       05:32:00    34931             11
10      1897634     05:32:00       05:32:00    34932             12
11      1897634     05:36:00       05:36:00    34933             13
12      1897634     05:36:00       05:36:00    34934             14
13      1897634     05:36:00       05:36:00    26073             15
14      1897634     05:36:00       05:36:00    26074             16
15      1897634     05:36:00       05:36:00    30861             17
16      1897634     05:36:00       05:36:00    26075             18
17      1897634     05:36:00       05:36:00    26076             19
18      1897634     05:36:00       05:36:00    26077             20
19      1897634     05:36:00       05:36:00    26078             21
20      1897634     05:36:00       05:36:00    26079             22
21      1897634     05:36:00       05:36:00    26080             23
22      1897634     05:42:00       05:42:00    26081             24
23      1897635     06:10:00       06:10:00    34922             25
24      1897635     06:10:00       06:10:00    34923             26
25      1897635     06:10:00       06:10:00    34924             27
26      1897635     06:10:00       06:10:00    34925             28
27      1897635     06:12:00       06:12:00    34926             29
28      1897635     06:12:00       06:12:00    34927             30
29      1897635     06:12:00       06:12:00    34928             31
...         ...          ...            ...      ...            ...
876848  1910106     19:04:00       19:04:00    25083            171
876849  1910106     19:04:00       19:04:00    29422            172
876850  1910106     19:04:00       19:04:00    25082            173
876851  1910106     19:04:00       19:04:00    25081            174
876852  1910106     19:04:00       19:04:00    25080            175
876853  1910106     19:04:00       19:04:00    29421            176
876854  1910106     19:04:00       19:04:00    25079            177
876855  1910106     19:04:00       19:04:00    25078            178
876856  1910106     19:04:00       19:04:00    29420            179
876857  1910106     19:04:00       19:04:00    25077            180
876858  1910106     19:04:00       19:04:00    25076            181
876859  1910106     19:04:00       19:04:00    25074            182
876860  1910106     19:04:00       19:04:00    25073            183
876861  1910106     19:04:00       19:04:00    25072            184
876862  1910106     19:04:00       19:04:00    25071            185
876863  1910106     19:04:00       19:04:00    25070            186
876864  1910106     19:04:00       19:04:00    25068            187
876865  1910106     19:04:00       19:04:00    25067            188
876866  1910106     19:04:00       19:04:00    25066            189
876867  1910106     19:04:00       19:04:00    25065            190
876868  1910106     19:04:00       19:04:00    25064            191
876869  1910106     19:04:00       19:04:00    25063            192
876870  1910106     19:04:00       19:04:00    25062            193
876871  1910106     19:04:00       19:04:00    25061            194
876872  1910106     19:04:00       19:04:00    25060            195
876873  1910106     19:04:00       19:04:00    25059            196
876874  1910106     19:04:00       19:04:00    25058            197
876875  1910106     19:04:00       19:04:00    25057            198
876876  1910106     19:04:00       19:04:00    25056            199
876877  1910106     19:33:00       19:33:00    32839            200

[876878 rows x 5 columns]

In [16]:
stops_df = pd.read_table('./stops.txt', sep=",", header=0, names=['stop_id','stop_lat','stop_lon','stop_name'])

In [17]:
stops_df

,stop_id,stop_lat,stop_lon,stop_name
0,1,42.184587,-87.931930,One Overlook Point ...
1,10,41.946691,-87.700269,Addison Francisco ...
2,100,42.041419,-87.699036,Demspter Dodge ...
3,1000,42.079864,-87.786988,Lake / Meadow ...
4,10000,41.957211,-87.860691,River/Cullom ...
5,10001,41.958317,-87.860949,River/Montrose ...
6,10002,41.959670,-87.861082,River/Moore ...
7,10003,41.962893,-87.861425,River/Eastwood ...
8,10004,41.863172,-87.931993,York/Brush Hill (NW) ...
9,10005,41.863879,-87.933306,Elmhurst Memorial Center for Health ...
10,10006,41.864734,-87.932086,York/Health Center Ent. Dr. ...
11,10007,41.862853,-87.931422,Brush Hill/York (SW) ...
12,1001,42.079860,-87.786548,Lake / Somerset ...
13,10014,42.050878,-87.677345,Sheridan Chicago Ave. ...
14,10015,41.850077,-87.833029,1st/Cermak (NW) ...
15,10016,41.753522,-87.886443,75th/Willow Springs ...
16,10017,41.756380,-87.886716,Willow Springs/5th Ave. ...
17,10018,41.760136,-87.886880,Willow Springs/71st Pl. ...
18,10019,41.763290,-87.887007,Willow Springs/Hillsdale ...
19,1002,42.079840,-87.785853,Lake / Brandon ...
20,10020,41.764571,-87.887054,Willow Springs/Cantigny ...
21,10021,41.765815,-87.887106,Willow Springs/Crestview ...
22,10022,41.768100,-87.887172,Willow Springs/67th ...
23,10023,41.768796,-87.887172,Willow Springs/Natasha ...
24,10024,41.769808,-87.887208,Willow Springs/Joliet ...
25,10025,41.771221,-87.884377,Joliet/Stalford ...
26,10026,41.773128,-87.880155,Joliet/64th ...
27,10027,41.774181,-87.877762,Joliet/Brainard ...
28,10028,41.775107,-87.875713,Joliet/Constance ...
29,10029,41.776135,-87.873408,Joliet/Kensington ...
...,...,...,...,...
34218,9972,41.926502,-87.865186,Rose/Richard ...
34219,9973,41.928784,-87.865284,Rose/Johanna ...
34220,9974,41.929360,-87.865328,Rose/Grand ...
34221,9975,41.931497,-87.865363,Rose/Chestnut ...
34222,9976,41.933347,-87.865414,Rose/Schiller ...
34223,9977,41.935100,-87.865528,Rose/Minneapolis ...
34224,9978,41.935632,-87.865536,Rose/Franklin ...
34225,9979,41.937102,-87.865601,Rose/Belmont/Pacific ...
34226,998,42.079891,-87.790241,Lake / Hawthorne ...
34227,9980,41.938713,-87.865656,Rose/Gage ...
34228,9981,41.940515,-87.865752,Rose/King ...
34229,9982,41.942127,-87.865845,Rose/Nerbonne ...
34230,9983,41.942981,-87.865834,Rose/Britta ...
34231,9984,41.944171,-87.865936,Rose/Addison ...
34232,9985,41.945947,-87.866001,25th/Waveland ...
34233,9986,41.947797,-87.866432,25th/Ivanhoe/Rose ...
34234,9987,41.949049,-87.868913,25th/Cary ...
34235,9988,41.950399,-87.870874,Ruby/25th ...
34236,9989,41.951255,-87.871113,Ruby/Soreng/Eden ...
34237,999,42.079873,-87.788459,Lake / Canterbury ...
34238,9990,41.953172,-87.871131,Ruby/Belle Plaine ...
34239,9991,41.955107,-87.871136,Irving Park/25th/Ruby ...
34240,9992,41.955367,-87.869680,Irving Park/Atlantic ...
34241,9993,41.955202,-87.868531,Irving Park/Wagner ...
34242,9994,41.954580,-87.863737,Irving Park/Wesley ...
34243,9995,41.954460,-87.862932,Irving Park/Grace ...
34244,9996,41.954292,-87.861676,Irving Park/Kolze ...
34245,9997,41.954122,-87.860433,Irving Park/Old River ...
34246,9998,41.953934,-87.858891,Irving Park/Bobby ...
34247,9999,41.953749,-87.856901,Irving Park/River ...

In [10]:
trips_df = pd.read_table('./trips.txt', sep=",", header=0, names=['route_id','trip_id','service_id',\
                                                                  'direction_id','block_id'])

In [11]:
trips_df

       route_id  trip_id  service_id  direction_id  block_id
0         37671  1900289          32             1    289671
1         37566  1900283          31             1    289693
2         37567  1906009          29             1    289799
3         37504  1900394          32             0    289710
4         37566  1900493          31             0    289717
5         37529  1904818          32             1    289772
6         37685  1900640          32             0    289753
7         37587  1900417          32             1    289743
8         37575  1904368          32             0    289816
9         37507  1904794          32             0    289848
10        37626  1903987          27             0    289842
11        37626  1904119          32             1    289862
12        37652  1904098          32             1    289938
13        37545  1904328          32             1    289962
14        37578  1904304          32             1    289993
15        37654  1904737          32             1    289991
16        37638  1902059          32             1    290136
17        37659  1902271          32             1    290179
18        37659  1902599          32             1    290171
19        37659  1901663          32             0    290166
20        37636  1902357          32             0    290199
21        37636  1901856          32             0    290205
22        37624  1902638          32             0    290287
23        37574  1901938          32             0    290268
24        37624  1902161          32             0    290309
25        37653  1902129          32             0    290379
26        37661  1901965          32             1    290314
27        37631  1902040          32             1    290406
28        37653  1901926          32             1    290401
29        37653  1901880          32             0    290398
...         ...      ...         ...           ...       ...
11632     37510  1898692          32             1    291280
11633     37514  1903090          32             0    291304
11634     37535  1903274          32             1    291301
11635     37572  1898591          32             0    291293
11636     37681  1903189          32             0    291310
11637     37615  1902984          32             1    291307
11638     37548  1902851          32             0    291323
11639     37636  1903326          32             0    291337
11640     37683  1899863          31             1    291375
11641     37556  1899371          32             1    291379
11642     37606  1899674          31             1    291404
11643     37582  1899904          31             1    291399
11644     37606  1899624          31             1    291417
11645     37633  1899513          32             0    291410
11646     37606  1899669          31             0    291429
11647     37648  1899621          32             1    291428
11648     37582  1899829          32             1    291442
11649     37582  1899817          32             0    291441
11650     37692  1910048          32             0    291517
11651     37583  1899116          32             0    291573
11652     37612  1900088          32             0    291606
11653     37619  1898999          32             0    291633
11654     37619  1898963          32             1    291632
11655     37619  1898960          32             0    291632
11656     37506  1899008          32             0    291631
11657     37644  1898916          32             1    291650
11658     37627  1903893          29             0    291546
11659     37582  1899166          29             0    291394
11660     37655  1907507          29             0    291189
11661     37497  1899523          24             0    291387

[11662 rows x 5 columns]

In [28]:
a = stoptime_df.filter(['stop_id','arrival_time','departure_time'], axis=1)
a = a.sort_values(by=['stop_id'], ascending=True).reset_index(drop=True)

In [29]:
a

        stop_id arrival_time departure_time
0           104     23:41:00       23:41:00
1           104     13:24:00       13:24:00
2           104     19:25:00       19:25:00
3           104     07:55:00       07:55:00
4           104     15:22:00       15:22:00
5           104     16:25:00       16:25:00
6           104     15:01:00       15:01:00
7           104     12:24:00       12:24:00
8           104     18:24:00       18:24:00
9           104     12:28:00       12:28:00
10          104     06:27:00       06:27:00
11          104     07:13:00       07:13:00
12          104     21:58:00       21:58:00
13          104     10:23:00       10:23:00
14          104     06:43:00       06:43:00
15          104     09:09:00       09:09:00
16          104     16:01:00       16:01:00
17          104     16:31:00       16:31:00
18          104     11:31:00       11:31:00
19          104     18:54:00       18:54:00
20          104     09:03:00       09:03:00
21          104     24:11:00       24:11:00
22          104     11:24:00       11:24:00
23          104     21:44:00       21:44:00
24          104     10:10:00       10:10:00
25          104     15:01:00       15:01:00
26          104     17:56:00       17:56:00
27          104     13:31:00       13:31:00
28          104     18:05:00       18:05:00
29          104     12:01:00       12:01:00
...         ...          ...            ...
876848    35219     05:40:00       05:40:00
876849    35219     18:40:00       18:40:00
876850    35219     08:40:00       08:40:00
876851    35219     08:39:00       08:39:00
876852    35219     16:39:00       16:39:00
876853    35219     09:40:00       09:40:00
876854    35219     14:39:00       14:39:00
876855    35219     17:40:00       17:40:00
876856    35219     20:37:00       20:37:00
876857    35219     20:39:00       20:39:00
876858    35220     06:36:00       06:36:00
876859    35220     07:58:00       07:58:00
876860    35221     06:29:00       06:29:00
876861    35221     07:51:00       07:51:00
876862    35222     07:51:00       07:51:00
876863    35222     18:19:00       18:19:00
876864    35222     06:29:00       06:29:00
876865    35223     18:09:00       18:09:00
876866    35223     07:45:00       07:45:00
876867    35223     06:23:00       06:23:00
876868    35224     15:20:00       15:20:00
876869    35224     16:45:00       16:45:00
876870    35225     16:45:00       16:45:00
876871    35225     15:20:00       15:20:00
876872    35226     15:27:00       15:27:00
876873    35226     16:52:00       16:52:00
876874    35226     05:05:00       05:05:00
876875    35227     15:33:00       15:33:00
876876    35227     16:58:00       16:58:00
876877    35227     05:13:00       05:13:00

[876878 rows x 3 columns]

In [35]:
f = pd.merge(stops_df, stoptime_df, on='stop_id')

In [36]:
f

,stop_id,stop_lat,stop_lon,stop_name,trip_id,arrival_time,departure_time,stop_sequence
0,10000,41.957211,-87.860691,River/Cullom ...,1908577,07:35:00,07:35:00,206
1,10000,41.957211,-87.860691,River/Cullom ...,1908605,06:05:00,06:05:00,123
2,10000,41.957211,-87.860691,River/Cullom ...,1908609,09:05:00,09:05:00,494
3,10000,41.957211,-87.860691,River/Cullom ...,1908711,07:05:00,07:05:00,256
4,10000,41.957211,-87.860691,River/Cullom ...,1908822,05:35:00,05:35:00,14
5,10000,41.957211,-87.860691,River/Cullom ...,1908917,06:35:00,06:35:00,123
6,10000,41.957211,-87.860691,River/Cullom ...,1908919,08:35:00,08:35:00,340
7,10000,41.957211,-87.860691,River/Cullom ...,1909059,14:05:00,14:05:00,609
8,10000,41.957211,-87.860691,River/Cullom ...,1909061,16:05:00,16:05:00,826
9,10000,41.957211,-87.860691,River/Cullom ...,1909063,18:10:00,18:10:00,1043
10,10000,41.957211,-87.860691,River/Cullom ...,1909065,20:10:00,20:10:00,1260
11,10000,41.957211,-87.860691,River/Cullom ...,1909067,22:15:00,22:15:00,1477
12,10000,41.957211,-87.860691,River/Cullom ...,1909204,11:05:00,11:05:00,381
13,10000,41.957211,-87.860691,River/Cullom ...,1909208,14:35:00,14:35:00,730
14,10000,41.957211,-87.860691,River/Cullom ...,1909213,08:05:00,08:05:00,123
15,10000,41.957211,-87.860691,River/Cullom ...,1909318,10:05:00,10:05:00,228
16,10000,41.957211,-87.860691,River/Cullom ...,1909326,12:05:00,12:05:00,368
17,10000,41.957211,-87.860691,River/Cullom ...,1909340,13:05:00,13:05:00,374
18,10000,41.957211,-87.860691,River/Cullom ...,1909380,15:05:00,15:05:00,436
19,10000,41.957211,-87.860691,River/Cullom ...,1909382,17:05:00,17:05:00,653
20,10000,41.957211,-87.860691,River/Cullom ...,1909384,19:10:00,19:10:00,870
21,10000,41.957211,-87.860691,River/Cullom ...,1909386,21:10:00,21:10:00,1087
22,10000,41.957211,-87.860691,River/Cullom ...,1909453,13:35:00,13:35:00,14
23,10000,41.957211,-87.860691,River/Cullom ...,1909455,15:35:00,15:35:00,231
24,10000,41.957211,-87.860691,River/Cullom ...,1909457,17:35:00,17:35:00,448
25,10000,41.957211,-87.860691,River/Cullom ...,1909482,16:35:00,16:35:00,284
26,10001,41.958317,-87.860949,River/Montrose ...,1908577,07:35:00,07:35:00,205
27,10001,41.958317,-87.860949,River/Montrose ...,1908605,06:05:00,06:05:00,122
28,10001,41.958317,-87.860949,River/Montrose ...,1908609,09:05:00,09:05:00,493
29,10001,41.958317,-87.860949,River/Montrose ...,1908711,07:05:00,07:05:00,255
...,...,...,...,...,...,...,...,...
876848,9998,41.953934,-87.858891,Irving Park/Bobby ...,1909453,13:44:00,13:44:00,16
876849,9998,41.953934,-87.858891,Irving Park/Bobby ...,1909455,15:44:00,15:44:00,233
876850,9998,41.953934,-87.858891,Irving Park/Bobby ...,1909457,17:44:00,17:44:00,450
876851,9998,41.953934,-87.858891,Irving Park/Bobby ...,1909482,16:44:00,16:44:00,286
876852,9999,41.953749,-87.856901,Irving Park/River ...,1908577,07:44:00,07:44:00,207
876853,9999,41.953749,-87.856901,Irving Park/River ...,1908605,06:14:00,06:14:00,124
876854,9999,41.953749,-87.856901,Irving Park/River ...,1908609,09:14:00,09:14:00,495
876855,9999,41.953749,-87.856901,Irving Park/River ...,1908711,07:14:00,07:14:00,257
876856,9999,41.953749,-87.856901,Irving Park/River ...,1908822,05:44:00,05:44:00,15
876857,9999,41.953749,-87.856901,Irving Park/River ...,1908917,06:44:00,06:44:00,124
876858,9999,41.953749,-87.856901,Irving Park/River ...,1908919,08:44:00,08:44:00,341
876859,9999,41.953749,-87.856901,Irving Park/River ...,1909059,14:14:00,14:14:00,610
876860,9999,41.953749,-87.856901,Irving Park/River ...,1909061,16:14:00,16:14:00,827
876861,9999,41.953749,-87.856901,Irving Park/River ...,1909063,18:19:00,18:19:00,1044
876862,9999,41.953749,-87.856901,Irving Park/River ...,1909065,20:19:00,20:19:00,1261
876863,9999,41.953749,-87.856901,Irving Park/River ...,1909067,22:24:00,22:24:00,1478
876864,9999,41.953749,-87.856901,Irving Park/River ...,1909204,11:14:00,11:14:00,382
876865,9999,41.953749,-87.856901,Irving Park/River ...,1909208,14:44:00,14:44:00,731
876866,9999,41.953749,-87.856901,Irving Park/River ...,1909213,08:14:00,08:14:00,124
876867,9999,41.953749,-87.856901,Irving Park/River ...,1909318,10:14:00,10:14:00,229
876868,9999,41.953749,-87.856901,Irving Park/River ...,1909326,12:14:00,12:14:00,369
876869,9999,41.953749,-87.856901,Irving Park/River ...,1909340,13:14:00,13:14:00,375
876870,9999,41.953749,-87.856901,Irving Park/River ...,1909380,15:14:00,15:14:00,437
876871,9999,41.953749,-87.856901,Irving Park/River ...,1909382,17:14:00,17:14:00,654
876872,9999,41.953749,-87.856901,Irving Park/River ...,1909384,19:19:00,19:19:00,871
876873,9999,41.953749,-87.856901,Irving Park/River ...,1909386,21:19:00,21:19:00,1088
876874,9999,41.953749,-87.856901,Irving Park/River ...,1909453,13:44:00,13:44:00,15
876875,9999,41.953749,-87.856901,Irving Park/River ...,1909455,15:44:00,15:44:00,232
876876,9999,41.953749,-87.856901,Irving Park/River ...,1909457,17:44:00,17:44:00,449
876877,9999,41.953749,-87.856901,Irving Park/River ...,1909482,16:44:00,16:44:00,285

In [36]:
f

,stop_id,stop_lat,stop_lon,stop_name,trip_id,arrival_time,departure_time,stop_sequence
0,10000,41.957211,-87.860691,River/Cullom ...,1908577,07:35:00,07:35:00,206
1,10000,41.957211,-87.860691,River/Cullom ...,1908605,06:05:00,06:05:00,123
2,10000,41.957211,-87.860691,River/Cullom ...,1908609,09:05:00,09:05:00,494
3,10000,41.957211,-87.860691,River/Cullom ...,1908711,07:05:00,07:05:00,256
4,10000,41.957211,-87.860691,River/Cullom ...,1908822,05:35:00,05:35:00,14
5,10000,41.957211,-87.860691,River/Cullom ...,1908917,06:35:00,06:35:00,123
6,10000,41.957211,-87.860691,River/Cullom ...,1908919,08:35:00,08:35:00,340
7,10000,41.957211,-87.860691,River/Cullom ...,1909059,14:05:00,14:05:00,609
8,10000,41.957211,-87.860691,River/Cullom ...,1909061,16:05:00,16:05:00,826
9,10000,41.957211,-87.860691,River/Cullom ...,1909063,18:10:00,18:10:00,1043
10,10000,41.957211,-87.860691,River/Cullom ...,1909065,20:10:00,20:10:00,1260
11,10000,41.957211,-87.860691,River/Cullom ...,1909067,22:15:00,22:15:00,1477
12,10000,41.957211,-87.860691,River/Cullom ...,1909204,11:05:00,11:05:00,381
13,10000,41.957211,-87.860691,River/Cullom ...,1909208,14:35:00,14:35:00,730
14,10000,41.957211,-87.860691,River/Cullom ...,1909213,08:05:00,08:05:00,123
15,10000,41.957211,-87.860691,River/Cullom ...,1909318,10:05:00,10:05:00,228
16,10000,41.957211,-87.860691,River/Cullom ...,1909326,12:05:00,12:05:00,368
17,10000,41.957211,-87.860691,River/Cullom ...,1909340,13:05:00,13:05:00,374
18,10000,41.957211,-87.860691,River/Cullom ...,1909380,15:05:00,15:05:00,436
19,10000,41.957211,-87.860691,River/Cullom ...,1909382,17:05:00,17:05:00,653
20,10000,41.957211,-87.860691,River/Cullom ...,1909384,19:10:00,19:10:00,870
21,10000,41.957211,-87.860691,River/Cullom ...,1909386,21:10:00,21:10:00,1087
22,10000,41.957211,-87.860691,River/Cullom ...,1909453,13:35:00,13:35:00,14
23,10000,41.957211,-87.860691,River/Cullom ...,1909455,15:35:00,15:35:00,231
24,10000,41.957211,-87.860691,River/Cullom ...,1909457,17:35:00,17:35:00,448
25,10000,41.957211,-87.860691,River/Cullom ...,1909482,16:35:00,16:35:00,284
26,10001,41.958317,-87.860949,River/Montrose ...,1908577,07:35:00,07:35:00,205
27,10001,41.958317,-87.860949,River/Montrose ...,1908605,06:05:00,06:05:00,122
28,10001,41.958317,-87.860949,River/Montrose ...,1908609,09:05:00,09:05:00,493
29,10001,41.958317,-87.860949,River/Montrose ...,1908711,07:05:00,07:05:00,255
...,...,...,...,...,...,...,...,...
876848,9998,41.953934,-87.858891,Irving Park/Bobby ...,1909453,13:44:00,13:44:00,16
876849,9998,41.953934,-87.858891,Irving Park/Bobby ...,1909455,15:44:00,15:44:00,233
876850,9998,41.953934,-87.858891,Irving Park/Bobby ...,1909457,17:44:00,17:44:00,450
876851,9998,41.953934,-87.858891,Irving Park/Bobby ...,1909482,16:44:00,16:44:00,286
876852,9999,41.953749,-87.856901,Irving Park/River ...,1908577,07:44:00,07:44:00,207
876853,9999,41.953749,-87.856901,Irving Park/River ...,1908605,06:14:00,06:14:00,124
876854,9999,41.953749,-87.856901,Irving Park/River ...,1908609,09:14:00,09:14:00,495
876855,9999,41.953749,-87.856901,Irving Park/River ...,1908711,07:14:00,07:14:00,257
876856,9999,41.953749,-87.856901,Irving Park/River ...,1908822,05:44:00,05:44:00,15
876857,9999,41.953749,-87.856901,Irving Park/River ...,1908917,06:44:00,06:44:00,124
876858,9999,41.953749,-87.856901,Irving Park/River ...,1908919,08:44:00,08:44:00,341
876859,9999,41.953749,-87.856901,Irving Park/River ...,1909059,14:14:00,14:14:00,610
876860,9999,41.953749,-87.856901,Irving Park/River ...,1909061,16:14:00,16:14:00,827
876861,9999,41.953749,-87.856901,Irving Park/River ...,1909063,18:19:00,18:19:00,1044
876862,9999,41.953749,-87.856901,Irving Park/River ...,1909065,20:19:00,20:19:00,1261
876863,9999,41.953749,-87.856901,Irving Park/River ...,1909067,22:24:00,22:24:00,1478
876864,9999,41.953749,-87.856901,Irving Park/River ...,1909204,11:14:00,11:14:00,382
876865,9999,41.953749,-87.856901,Irving Park/River ...,1909208,14:44:00,14:44:00,731
876866,9999,41.953749,-87.856901,Irving Park/River ...,1909213,08:14:00,08:14:00,124
876867,9999,41.953749,-87.856901,Irving Park/River ...,1909318,10:14:00,10:14:00,229
876868,9999,41.953749,-87.856901,Irving Park/River ...,1909326,12:14:00,12:14:00,369
876869,9999,41.953749,-87.856901,Irving Park/River ...,1909340,13:14:00,13:14:00,375
876870,9999,41.953749,-87.856901,Irving Park/River ...,1909380,15:14:00,15:14:00,437
876871,9999,41.953749,-87.856901,Irving Park/River ...,1909382,17:14:00,17:14:00,654
876872,9999,41.953749,-87.856901,Irving Park/River ...,1909384,19:19:00,19:19:00,871
876873,9999,41.953749,-87.856901,Irving Park/River ...,1909386,21:19:00,21:19:00,1088
876874,9999,41.953749,-87.856901,Irving Park/River ...,1909453,13:44:00,13:44:00,15
876875,9999,41.953749,-87.856901,Irving Park/River ...,1909455,15:44:00,15:44:00,232
876876,9999,41.953749,-87.856901,Irving Park/River ...,1909457,17:44:00,17:44:00,449
876877,9999,41.953749,-87.856901,Irving Park/River ...,1909482,16:44:00,16:44:00,285